print(len("12345"))
print(type(123))
print(type("123"))
print(type(0.21))
print(type(True))
print(int("123")+int("324"))
int()
float()
str()
bool()
print("Number of letters in your name: "+ str(len(input("Enter your name: "))))